---
- name: Install etcd service
  hosts: ubuntu_desktop
  gather_facts: no
  become: true

  tasks:
    - name: Include configurations from config.yaml
      include_vars:
        file: config.yaml
        name: configs

    # Remove existing etcd
    - name: Check if etcd is running
      command: systemctl is-active etcd
      register: etcd_status
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Stop etcd service if running
      systemd:
        name: etcd
        state: stopped
      when: etcd_status.stdout == "active"

    - name: Remove /tmp/etcd-download-test folder
      file:
        path: /tmp/etcd-download-test
        state: absent

    - name: Clean up previous etcd installation files
      file:
        path: "/tmp/etcd-{{ configs.etcd_version }}-linux-amd64.tar.gz"
        state: absent

    - name: Create a temporary directory for etcd download
      file:
        path: "/tmp/etcd-download-test"
        state: directory

    # The Url might need to be updated
    - name: Download etcd binary
      get_url:
        url: "{{ configs.download_url }}/{{ configs.etcd_version }}/etcd-{{ configs.etcd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd-{{ configs.etcd_version }}-linux-amd64.tar.gz"

    - name: Extract etcd binary
      command: "tar xzvf /tmp/etcd-{{ configs.etcd_version }}-linux-amd64.tar.gz -C /tmp/etcd-download-test --strip-components=1"

    - name: Remove the downloaded archive
      file:
        path: "/tmp/etcd-{{ configs.etcd_version }}-linux-amd64.tar.gz"
        state: absent

    - name: Check etcd version
      command: "/tmp/etcd-download-test/etcd --version"
      register: etcd_version_output

    - name: Print etcd version
      debug:
        var: etcd_version_output.stdout

    - name: Check etcdctl version
      command: "/tmp/etcd-download-test/etcdctl version"
      register: etcdctl_version_output

    - name: Print etcdctl version
      debug:
        var: etcdctl_version_output.stdout

    - name: Remove etcd.service if exists
      file:
        path: "/etc/systemd/system/etcd.service"
        state: absent
    
    - name: Copy etcd.service unit file
      template:
        src: etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Reload systemd
      
    - name: Start etcd service
      systemd:
        name: etcd
        state: started
      
  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes