---
- name: Uninstall etcd service
  hosts: ubuntu_desktop # Change hosts
  gather_facts: true
  become: true

  tasks:
    - name: Include task files
      include_tasks: "{{ item }}"
      loop:
        - subtasks/clean_up.yaml
  
  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes