---
- name: Install etcd service
  hosts: all # Change hosts
  gather_facts: true
  become: true

  tasks:
    - name: Include task files
      include_tasks: "{{ item }}"
      loop:
        - subtasks/import_configs.yaml
        - ../headers/determine_arch.yaml
        - subtasks/clean_up.yaml

    - name: Create a temporary directory for etcd download
      file:
        path: "/tmp/etcd-download-test"
        state: directory

    # The Url might need to be updated
    - name: Download etcd binary
      get_url:
        url: "{{ configs.download_url }}/{{ configs.etcd_version }}/etcd-{{ configs.etcd_version }}-linux-{{ architecture_type }}.tar.gz"
        dest: "/tmp/etcd-{{ configs.etcd_version }}-linux-{{ architecture_type }}.tar.gz"

    - name: Extract etcd binary
      command: "tar xzvf /tmp/etcd-{{ configs.etcd_version }}-linux-{{ architecture_type }}.tar.gz -C /tmp/etcd-download-test --strip-components=1"

    - name: Remove the downloaded archive
      file:
        path: "/tmp/etcd-{{ configs.etcd_version }}-linux-{{ architecture_type }}.tar.gz"
        state: absent

    - name: Check etcd version
      command: "/tmp/etcd-download-test/etcd --version"
      register: etcd_version_output
      environment:
        ETCD_UNSUPPORTED_ARCH: "{{ 'arm64' if architecture_type == 'arm64' else '' }}"

    - name: Print etcd version
      debug:
        var: etcd_version_output.stdout

    - name: Check etcdctl version
      command: "/tmp/etcd-download-test/etcdctl version"
      register: etcdctl_version_output

    - name: Print etcdctl version
      debug:
        var: etcdctl_version_output.stdout
    
    - name: Copy etcd.service unit file
      template:
        src: template/etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        owner: root
        group: root
        mode: '0644'
    
    - name: Reload systemd
      command: systemctl daemon-reload
      
    - name: Start etcd service
      systemd:
        name: etcd
        state: started
